AWSTemplateFormatVersion: 2010-09-09
Description: AWSrecon A multi-threaded AWS security-focused inventory collection tool written in Ruby.
Parameters:
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: Please enter the VPCId.
  CustomerAlias:
    Type: String
    Description: Please enter the CustomerAlias(example = bank123)
  SubnetId:
    Type: 'AWS::EC2::Subnet::Id'
    Description: Please enter the subnetId.
  InstanceType:
    Type: String
    Default: t3a.small
    AllowedValues:
      - t3a.xlarge
      - t3a.medium
      - t3a.2xlarge
      - t3a.large
      - t3a.small
      - t3a.micro
    Description: Please enter the instance type example t3a.medium,t3a.large,t3a.xlarge,t3a.2xlarge
  AmiID:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Description: Query for the latest Amazon Linux AMI IDs using AWS Systems Manager Parameter Store
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  AwsRegion:
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - af-south-1
      - ap-east-1
      - ap-southeast-3
      - ap-southeast-2
      - ap-southeast-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-south-1
      - eu-west-3
      - eu-north-1
      - me-south-1
      - me-central-1
      - sa-east-1
    Description: Enter any region

Resources:
  awsreconSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${CustomerAlias}-awsreconScannerInstance-SG'
      VpcId: !Ref VpcId
      GroupDescription: "Allow SSH/HTTPS traffic"
      Tags:
        - Key: Name
          Value: !Sub '${CustomerAlias}-awsreconSecurityGroup'
        - Key: CustomerAlias
          Value: !Sub '${CustomerAlias}'
  Ec2SsmIamRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess            
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Policies:
        - PolicyName: !Sub ${CustomerAlias}-sts-assume-role
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "sts:*"
                Resource: "*"          
        - PolicyName: !Sub ${CustomerAlias}-access-to-specific-S3-bucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "s3:*"
                Effect: "Allow"
                Resource:
                  - !Sub arn:aws:s3:::${CustomerAlias}-scans-results
                  - !Sub arn:aws:s3:::${CustomerAlias}-scans-results/*
      Tags:
        - Key: Name
          Value: !Sub '${CustomerAlias}-Ec2SsmIamRole-awsrecon'
        - Key: CustomerAlias
          Value: !Sub '${CustomerAlias}'
  Ec2SsmInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: [!Ref Ec2SsmIamRole]
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketName: !Sub '${CustomerAlias}-scans-results'
  awsreconScannerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: '30'
            DeleteOnTermination: 'true'
            Encrypted: 'true'
      SecurityGroupIds:
        - !Ref awsreconSecurityGroup
      SubnetId: !Ref SubnetId
      IamInstanceProfile: !Ref Ec2SsmInstanceProfile
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            sudo yum update -y && sudo yum upgrade -y
            sudo yum install -y python3 jq git awscli
            cd /home/ec2-user
            sudo su - ec2-user -s /bin/bash -c 'git clone https://github.com/darkbitio/aws-recon'
            sudo su - ec2-user -s /bin/bash -c 'chown -R ec2-user:ec2-user /home/ec2-user/aws-recon'
            cd /home/ec2-user/aws-recon
            sudo su - ec2-user -s /bin/bash -c 'sudo amazon-linux-extras install ruby3.0'
            sudo su - ec2-user -s /bin/bash -c 'gem install aws_recon'
            sleep 3s
            sudo curl -L -o /home/ec2-user/aws-recon/aws-vault https://github.com/99designs/aws-vault/releases/latest/download/aws-vault-linux-amd64
            sudo chmod 755 /home/ec2-user/aws-recon/aws-vault



            cd /home/ec2-user/aws-recon
     #       pip3 install -r requirements.txt
      #      export url=$(aws ssm get-parameter --name=${CustomerAlias}-${IdentifierId}-url --region us-east-1 --with-decryption | jq -r '.Parameter | .Value')
    #        ./awsrecon.py scan $url -p descriptions refs >> awsrecon.output.json
      #      sudo su - ec2-user -s /bin/bash -c 'aws s3 cp /home/ec2-user/awsrecon/awsrecon.output.json s3://${CustomerAlias}-scans-results/awsrecon/'


      Tags:
        - Key: Name
          Value: !Sub '${CustomerAlias}-EC2-CredHunter'
        - Key: CustomerAlias
          Value: !Sub '${CustomerAlias}'
Outputs:
  InstanceId:
    Description: awsrecon InstanceId
    Value: !Ref 'awsreconScannerInstance'
    Export:
      Name: !Sub '${CustomerAlias}-awsreconScannerInstanceId'
  SgId:
    Description: awsreconScannerInstance Security Group Id
    Value: !Ref 'awsreconSecurityGroup'
