AWSTemplateFormatVersion: 2010-09-09
Description: Customer Cloud Scanners Credentials

Parameters:
  CustomerAlias:
    Type: String
    Description: Please enter the CustomerAlias(example = bank123)
  RepoName:
    Type: String
    Description: Please enter the URL.
  IdentifierId:
    Type: String
    Description: Please enter the Identifier Id for the repositories scan.
    Default: CredHunter
  Token:
    Type: String
    Description: Please enter the Identifier Id for the repositories scan.

Resources:
  RepoNameAndIdetifierId:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${CustomerAlias}-CredHunter-repositories'
      Description: Encrypted CredHunter Repositories
      SecretString: !Sub '{"RepoName":"${RepoName}","IdentifierId":"${IdentifierId}","Token":"${Token}"}'
      Tags:
        - Key: Name
          Value: !Sub '${CustomerAlias}-CredHunter-repositories'
        - Key: CustomerAlias
          Value: !Sub '${CustomerAlias}'